"""empty message

Revision ID: 49a28ae343d7
Revises: ba265e5704c3
Create Date: 2025-11-26 21:54:01.869096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a28ae343d7'
down_revision = 'ba265e5704c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_cost', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holding', schema=None) as batch_op:
        batch_op.drop_column('book_cost')

    # ### end Alembic commands ###
