"""added indexing on holding table

Revision ID: 6d15b8c9a269
Revises: 49a28ae343d7
Create Date: 2025-11-28 00:43:04.806576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d15b8c9a269'
down_revision = '49a28ae343d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holding', schema=None) as batch_op:
        batch_op.create_index('idx_holding_portfolio_stock', ['portfolio_id', 'stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holding_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holding_stock_id'), ['stock_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holding_stock_id'))
        batch_op.drop_index(batch_op.f('ix_holding_portfolio_id'))
        batch_op.drop_index('idx_holding_portfolio_stock')

    # ### end Alembic commands ###
